apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: confluence-vacations
spec:
  schedule: "0 10 14 ? * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: confluence-vacations
            image: jkrnak/ical-slack-vacations
            env:
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: cronsecret
                  key: webhook-url
            - name: ICAL_URL
              valueFrom:
                secretKeyRef:
                  name: cronsecret
                  key: ical-url
          restartPolicy: OnFailure
